# Generated by Django 4.0.3 on 2023-01-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empno', models.IntegerField(verbose_name=5)),
                ('Ename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Job', models.CharField(max_length=30)),
                ('Mgr', models.IntegerField(verbose_name=5)),
                ('Hiredate', models.DateField()),
                ('Sal', models.IntegerField(verbose_name=6)),
                ('Comm', models.IntegerField(verbose_name=5)),
                ('Deptno', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
                ('Deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
